# Generated by Django 4.1.3 on 2022-11-16 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='request',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
    ]
