# Generated by Django 4.1.3 on 2022-11-16 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0002_rename_content_request_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
