# Generated by Django 4.1.3 on 2022-11-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0003_request_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='publish_date',
        ),
    ]
