# Generated by Django 4.1.3 on 2022-11-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0004_remove_request_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=256)),
                ('requestt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketer.request')),
            ],
        ),
    ]
