# Generated by Django 4.1.3 on 2022-11-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0005_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
    ]
