# Generated by Django 4.1.3 on 2022-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketer', '0006_remove_offer_amount_remove_offer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=650)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
